name: s1ard_dev
channels:
  - conda-forge
  - s1-etad
  - dharpa
dependencies:
  - asf_search
  - cesard>=1.0.2
  - click>=7.1.0
  - gdal>=3.5.0
  - geopandas
  - lxml
  - multiformats>=0.3.1
  - numpy<2.0
  - packaging
  - pandas
  - pip
  - pyproj
  - pyroSAR>=0.31.0
  - pystac>=1.8.0,<1.11.0
  - pystac-client>=0.7.0
  - python>=3.10
  - python-dateutil
  - requests
  - s1etad>=0.5.3
  - s1etad_tools>=0.8.1
  - scipy
  - shapely
  - spatialist>=0.16.0
  - filelock  # needed for sphinx_toolbox.collapse
  - ipython  # for notebook code highlighting
  - nbsphinx
  - pytest  # for unit tests
  - sphinx
  - sphinx-toolbox
  - sphinx_rtd_theme>=2.0
  - sphinxcontrib-bibtex>=2.2
